- name: Instalando Apache e PHP
  hosts: all
  tasks:
    - name: Instalando no Ubuntu
      apt:
        name: apache2
        state: present
        name: php7.0
        state: present
        name: libapache2-mod-php7.0
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Instalando Httpd no CentOS
      yum:
        name: httpd
        state: present
        name: php
        state: present
      when: ansible_distribution == "CentOS"
    - name: Copiando index.php
      copy:
        src: /etc/ansible/index.php
        dest: /var/www/html/index.php
    - name: Iniciando Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
    - name: Iniciando CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"

